//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlindTyper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlindTyper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your accuracy is .
        /// </summary>
        public static string TEXT_Accuracy_part1 {
            get {
                return ResourceManager.GetString("TEXT_Accuracy_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!.
        /// </summary>
        public static string TEXT_Accuracy_part2 {
            get {
                return ResourceManager.GetString("TEXT_Accuracy_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are done!.
        /// </summary>
        public static string TEXT_FinishMessage {
            get {
                return ResourceManager.GetString("TEXT_FinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  / .
        /// </summary>
        public static string TEXT_Score_mid {
            get {
                return ResourceManager.GetString("TEXT_Score_mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlindTyper.
        /// </summary>
        public static string UI_AppTitle {
            get {
                return ResourceManager.GetString("UI_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        public static string UI_ButtonImportFileText {
            get {
                return ResourceManager.GetString("UI_ButtonImportFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        public static string UI_LabelPressAnyKeyText {
            get {
                return ResourceManager.GetString("UI_LabelPressAnyKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is removed in code..
        /// </summary>
        public static string UI_RichTextBoxDefaultText {
            get {
                return ResourceManager.GetString("UI_RichTextBoxDefaultText", resourceCulture);
            }
        }
    }
}
